
wget http://nuttcp.net/nuttcp/nuttcp-7.3.3/nuttcp-7.3.3.c
gcc nuttcp-7.3.3.c -o nuttcp-7.3.3

# then use it by ./nuttcp-7.3.3 -S
# use it as if you are running an executable file generated by a C code
